name: Jekyll Themes
url: http://ppmanforthewin.github.io/jekyllthemes
description: Insert tagline here

permalink: /jekyllthemes

gems: [jekyll-paginate]

highlighter: rouge
paginate: 20

markdown: kramdown
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
